name: Continuous Integration Pipeline

on: [push]

env:
  IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/scalable-fastapi-aws

jobs:

  build-ci-image:
    name: Build CI Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag ${{ env.IMAGE }}:latest \
            --file ./ci_cd/python/Dockerfile \
            "."
      - name: Push image
        run: |
          docker push ${{ env.IMAGE }}:latest

  code-quality:
    name: Code quality checks
    runs-on: ubuntu-latest
    needs: build-ci-image
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Log in to GitHub Packages
      run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull image
      run: |
        docker pull ${{ env.IMAGE }}:latest || true
    - name: Build image
      run: |
        docker build \
        --cache-from ${{ env.IMAGE }}:latest \
        --tag ${{ env.IMAGE }}:latest \
        --file ./ci_cd/python/Dockerfile \
        "."
    - name: Run container
      run: |
          docker run \
          -d \
          --name scalable-fastapi-aws \
          ${{ env.IMAGE }}:latest
    - name: Flake8
      run: docker exec scalable-fastapi-aws poetry flake8 .
    - name: Black
      run: docker exec scalable-fastapi-aws poetry black . --check
    - name: isort
      run: docker exec scalable-fastapi-aws poetry isort . --check-only --profile black
